### ISSUE TITLE
camera.projection  is not a CameraProjection enumeration

### ISSUE THREAD

**Issue by omidud** [ZeroElectric/Raylib-CSharp-Vinculum#13]
is just minor issue
to assign this

 camera.projection = (int)CameraProjection.CAMERA_PERSPECTIVE; 
 
 I need to cast to int in front, can you chnage camera projection as  CameraProjection  please 
 like Raylib.cs do?
 
 
 Thanks

**Comment by Minmoose** [comment]
Because this project autogens the core bindings it copies the raylib spec one to one, as properties & fields are not overloadable this is unfixable without adding undue complexity to the project.

As a work around you can use the `camera.projection_` property to fix this, in the next update you will also be able to use `camera.Projection`.

**Comment by omidud** [comment]
Undertand, Thanks for the response.
